# Generated by Django 4.1.4 on 2023-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('company_name', models.CharField(max_length=200)),
                ('company_code', models.IntegerField(unique=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'private_tb',
                'managed': False,
            },
        ),
    ]
